# flake.nix
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    sops-nix.url = "github:Mic92/sops-nix";
  };
  outputs = { self, nixpkgs, sops-nix }:
    let
      lib = nixpkgs.lib; # Make lib available
      # Helper function to import all .nix files from a directory
      importModules = path:
        let
          dirContents = builtins.readDir path;
          nixFiles = lib.filterAttrs (name: type:
            type == "regular" && lib.strings.hasSuffix ".nix" name
          ) dirContents;
        in
        lib.mapAttrsToList (name: _: path + "/${name}") nixFiles;
    in {
      nixosConfigurations.homeserver = lib.nixosSystem {
        system = "x86_64-linux";
        modules =
          [
            sops-nix.nixosModules.sops
          ]
          ++ (importModules ./modules)
          ++ [
            # Inline module primarily for SOPS secret injection
            # and configuring the custom homeAssistant module
            ({ config, pkgs, lib, ... }: {

              # === SOPS Configuration ===
              sops.secrets.REOLINK_CAMERA_PASSWORD = {
                sopsFile = ./secrets/reolink-secrets.yaml;
                owner = "hass";
                group = "hass";
                mode = "0440";
              };

              # Ensure hass user is added to the 'keys' group
              users.users.hass.extraGroups = [ "keys" ];

              # Inject the secret file path using EnvironmentFile
              systemd.services."home-assistant".serviceConfig = {
                # Remove LoadCredential= if present from previous attempts
                LoadCredential = lib.mkForce null;
                # REMOVE the ExecStart override that caused the error
                # ExecStart = lib.mkForce null; # <-- REMOVE THIS LINE

                # Point EnvironmentFile to the path generated by sops.secrets
                EnvironmentFile = config.sops.secrets.REOLINK_CAMERA_PASSWORD.path;
              };
              # Dependencies remain the same
              systemd.services."home-assistant".wants = [ "sops-nix.service" ];
              systemd.services."home-assistant".after = [ "sops-nix.service" ];


              # === Configuration for the Custom Home Assistant Module ===
              modules.homeAssistant = {
                enable = true;
                latitude = "40.7128";
                longitude = "-74.0060";
                timeZone = "America/Toronto";
                unitSystem = "metric";
                reolink = {
                  enable = true;
                  cameras = {
                    "418" = {
                      host = "10.10.10.59";
                      username = "admin";
                      password = "!env_var REOLINK_CAMERA_PASSWORD";
                      port = 80;
                      channel = 0;
                      stream = "main";
                    };
                    "420" = {
                      host = "10.10.10.60";
                      username = "admin";
                      password = "!env_var REOLINK_CAMERA_PASSWORD";
                      port = 80;
                      channel = 0;
                      stream = "main";
                    };
                  };
                };
                extraComponents = [
                  "mqtt"
                  "zha"
                  "stream"
                  "ffmpeg"
                  "radio_browser"
                  "google_translate"
                ];
                extraPackages = py: with py; [
                  getmac
                  aiohomekit
                  pyqrcode
                  pypng
                  pillow
                  xmltodict
                  radios
                  gtts
                ];
              };
            })
          ];
      };
    };
}

